package ics

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Safety limits. A recurring event with no UNTIL and no COUNT is unbounded
// by definition, so the window is what terminates expansion — but a
// malformed rule must not be able to spin the fetcher goroutine either.
const (
	maxIterations  = 20000
	maxOccurrences = 2000
)

type rrule struct {
	freq       string
	interval   int
	count      int
	until      time.Time
	byDay      []weekdayNum
	byMonthDay []int
	byMonth    []time.Month
}

// weekdayNum is a BYDAY entry: a weekday with an optional ordinal, so "3MO"
// means the third Monday and "-1FR" the last Friday.
type weekdayNum struct {
	ord int
	day time.Weekday
}

// expandRRULE returns occurrence start times within [from, to].
func expandRRULE(rule string, start, from, to time.Time) ([]time.Time, error) {
	r, err := parseRRULE(rule)
	if err != nil {
		return nil, err
	}

	// An unbounded rule needs a window to terminate against. Without one we
	// would generate forever, so refuse rather than hang.
	if to.IsZero() && r.count == 0 && r.until.IsZero() {
		return nil, fmt.Errorf("unbounded RRULE %q with no window", rule)
	}

	limit := to
	if !r.until.IsZero() && (limit.IsZero() || r.until.Before(limit)) {
		limit = r.until
	}

	var (
		out   []time.Time
		iters int
	)

	// The cursor marks a recurrence *period*, not an occurrence.
	//
	// For MONTHLY and YEARLY it is normalised to the first of the period,
	// because Go's calendar arithmetic normalises overflow: adding one month
	// to 31 January yields 3 March, which silently skips February entirely.
	// Stepping day-1 to day-1 and deriving the occurrence within the period
	// avoids that whole class of bug.
	cursor := periodStart(r.freq, start)

	// Fast-forward rather than stepping through years of history one period
	// at a time.
	if !from.IsZero() && r.count == 0 {
		cursor = periodStart(r.freq, fastForward(r, cursor, from))
	}

	for {
		iters++
		if iters > maxIterations || len(out) >= maxOccurrences {
			break
		}
		if !limit.IsZero() && cursor.After(limit) {
			break
		}

		for _, occ := range occurrencesIn(r, cursor, start) {
			if occ.Before(start) {
				continue
			}
			if !limit.IsZero() && occ.After(limit) {
				continue
			}
			if !from.IsZero() && occ.Before(from) {
				// Still counts toward COUNT — a COUNT=10 rule that began
				// before the window has already spent some of its budget.
				if r.count > 0 {
					out = append(out, occ)
				}
				continue
			}
			out = append(out, occ)
		}

		if r.count > 0 && len(out) >= r.count {
			out = out[:r.count]
			break
		}

		next := advance(r, cursor)
		if !next.After(cursor) {
			// A rule that fails to advance would loop forever.
			break
		}
		cursor = next
	}

	// Drop the pre-window occurrences that were only kept to satisfy COUNT.
	if !from.IsZero() {
		filtered := out[:0]
		for _, t := range out {
			if !t.Before(from) {
				filtered = append(filtered, t)
			}
		}
		out = filtered
	}
	return out, nil
}

// periodStart normalises a time to the beginning of its recurrence period.
//
// Only MONTHLY and YEARLY need it: those are the frequencies whose advance
// step would otherwise overflow a short month.
func periodStart(freq string, t time.Time) time.Time {
	switch freq {
	case "MONTHLY":
		return time.Date(t.Year(), t.Month(), 1, 0, 0, 0, 0, t.Location())
	case "YEARLY":
		return time.Date(t.Year(), 1, 1, 0, 0, 0, 0, t.Location())
	default:
		return t
	}
}

// occurrencesIn returns the occurrences generated by one period at cursor.
func occurrencesIn(r rrule, cursor, start time.Time) []time.Time {
	switch r.freq {
	case "DAILY":
		return []time.Time{cursor}

	case "WEEKLY":
		if len(r.byDay) == 0 {
			return []time.Time{cursor}
		}
		// Walk the week containing cursor, starting Sunday.
		weekStart := cursor.AddDate(0, 0, -int(cursor.Weekday()))
		var out []time.Time
		for _, wd := range r.byDay {
			d := weekStart.AddDate(0, 0, int(wd.day))
			out = append(out, atTimeOf(d, start))
		}
		return out

	case "MONTHLY":
		var out []time.Time
		if len(r.byMonthDay) > 0 {
			for _, md := range r.byMonthDay {
				if d, ok := monthDay(cursor, md, start); ok {
					out = append(out, d)
				}
			}
			return out
		}
		if len(r.byDay) > 0 {
			for _, wd := range r.byDay {
				if d, ok := nthWeekday(cursor, wd, start); ok {
					out = append(out, d)
				}
			}
			return out
		}
		// No BY* rule: repeat on the same day-of-month as DTSTART. Months
		// too short for that day simply have no occurrence, which is what
		// RFC 5545 specifies — a 31st-of-the-month series skips February
		// rather than sliding to the 28th.
		if d, ok := monthDay(cursor, start.Day(), start); ok {
			return []time.Time{d}
		}
		return nil

	case "YEARLY":
		months := r.byMonth
		if len(months) == 0 {
			months = []time.Month{start.Month()}
		}
		var out []time.Time
		for _, m := range months {
			anchor := time.Date(cursor.Year(), m, 1, 0, 0, 0, 0, start.Location())
			if d, ok := monthDay(anchor, start.Day(), start); ok {
				out = append(out, d)
			}
		}
		return out

	default:
		return []time.Time{cursor}
	}
}

// advance steps the cursor by one interval.
func advance(r rrule, cursor time.Time) time.Time {
	n := r.interval
	if n <= 0 {
		n = 1
	}
	switch r.freq {
	case "DAILY":
		return cursor.AddDate(0, 0, n)
	case "WEEKLY":
		return cursor.AddDate(0, 0, 7*n)
	case "MONTHLY":
		return cursor.AddDate(0, n, 0)
	case "YEARLY":
		return cursor.AddDate(n, 0, 0)
	default:
		return cursor.AddDate(0, 0, n)
	}
}

// fastForward jumps the cursor close to `from` without stepping through
// every intervening period.
func fastForward(r rrule, start, from time.Time) time.Time {
	if !start.Before(from) {
		return start
	}
	n := r.interval
	if n <= 0 {
		n = 1
	}

	switch r.freq {
	case "DAILY":
		days := int(from.Sub(start).Hours() / 24)
		return start.AddDate(0, 0, (days/n)*n)
	case "WEEKLY":
		weeks := int(from.Sub(start).Hours() / 24 / 7)
		return start.AddDate(0, 0, 7*n*(weeks/n))
	case "MONTHLY":
		months := (from.Year()-start.Year())*12 + int(from.Month()-start.Month())
		if months > 0 {
			return start.AddDate(0, (months/n)*n, 0)
		}
	case "YEARLY":
		years := from.Year() - start.Year()
		if years > 0 {
			return start.AddDate((years/n)*n, 0, 0)
		}
	}
	return start
}

// atTimeOf places the clock time of ref onto the date of d.
func atTimeOf(d, ref time.Time) time.Time {
	return time.Date(d.Year(), d.Month(), d.Day(),
		ref.Hour(), ref.Minute(), ref.Second(), 0, ref.Location())
}

// monthDay resolves a BYMONTHDAY entry, where negatives count from the end.
func monthDay(cursor time.Time, md int, ref time.Time) (time.Time, bool) {
	year, month := cursor.Year(), cursor.Month()
	last := time.Date(year, month+1, 0, 0, 0, 0, 0, ref.Location()).Day()

	day := md
	if md < 0 {
		day = last + 1 + md
	}
	if day < 1 || day > last {
		return time.Time{}, false
	}
	return time.Date(year, month, day,
		ref.Hour(), ref.Minute(), ref.Second(), 0, ref.Location()), true
}

// nthWeekday resolves entries like "3MO" (third Monday) or "-1FR" (last
// Friday) within the cursor's month.
func nthWeekday(cursor time.Time, wd weekdayNum, ref time.Time) (time.Time, bool) {
	year, month := cursor.Year(), cursor.Month()
	first := time.Date(year, month, 1, 0, 0, 0, 0, ref.Location())
	last := time.Date(year, month+1, 0, 0, 0, 0, 0, ref.Location()).Day()

	var days []int
	offset := (int(wd.day) - int(first.Weekday()) + 7) % 7
	for d := 1 + offset; d <= last; d += 7 {
		days = append(days, d)
	}
	if len(days) == 0 {
		return time.Time{}, false
	}

	var day int
	switch {
	case wd.ord == 0:
		// No ordinal in a MONTHLY rule means every matching weekday; the
		// caller handles only the first, which is the common case for
		// "every Monday" expressed monthly.
		day = days[0]
	case wd.ord > 0:
		if wd.ord > len(days) {
			return time.Time{}, false
		}
		day = days[wd.ord-1]
	default:
		if -wd.ord > len(days) {
			return time.Time{}, false
		}
		day = days[len(days)+wd.ord]
	}

	return time.Date(year, month, day,
		ref.Hour(), ref.Minute(), ref.Second(), 0, ref.Location()), true
}

func parseRRULE(rule string) (rrule, error) {
	r := rrule{interval: 1}

	for _, part := range strings.Split(rule, ";") {
		key, value, found := strings.Cut(part, "=")
		if !found {
			continue
		}
		switch strings.ToUpper(key) {
		case "FREQ":
			r.freq = strings.ToUpper(value)
		case "INTERVAL":
			if n, err := strconv.Atoi(value); err == nil && n > 0 {
				r.interval = n
			}
		case "COUNT":
			if n, err := strconv.Atoi(value); err == nil && n > 0 {
				r.count = n
			}
		case "UNTIL":
			if t, _, ok := parseTime(value, map[string]string{}, time.UTC); ok {
				r.until = t
			}
		case "BYDAY":
			for _, d := range strings.Split(value, ",") {
				if wd, ok := parseWeekdayNum(d); ok {
					r.byDay = append(r.byDay, wd)
				}
			}
		case "BYMONTHDAY":
			for _, d := range strings.Split(value, ",") {
				if n, err := strconv.Atoi(strings.TrimSpace(d)); err == nil {
					r.byMonthDay = append(r.byMonthDay, n)
				}
			}
		case "BYMONTH":
			for _, d := range strings.Split(value, ",") {
				if n, err := strconv.Atoi(strings.TrimSpace(d)); err == nil && n >= 1 && n <= 12 {
					r.byMonth = append(r.byMonth, time.Month(n))
				}
			}
		}
	}

	if r.freq == "" {
		return r, fmt.Errorf("RRULE %q has no FREQ", rule)
	}
	switch r.freq {
	case "DAILY", "WEEKLY", "MONTHLY", "YEARLY":
	default:
		// SECONDLY/MINUTELY/HOURLY exist but have no business on a mirror,
		// and expanding them over a 90-day window would be millions of
		// occurrences.
		return r, fmt.Errorf("unsupported FREQ %q", r.freq)
	}
	return r, nil
}

var weekdayCodes = map[string]time.Weekday{
	"SU": time.Sunday, "MO": time.Monday, "TU": time.Tuesday,
	"WE": time.Wednesday, "TH": time.Thursday, "FR": time.Friday,
	"SA": time.Saturday,
}

func parseWeekdayNum(s string) (weekdayNum, bool) {
	s = strings.ToUpper(strings.TrimSpace(s))
	if len(s) < 2 {
		return weekdayNum{}, false
	}

	code := s[len(s)-2:]
	day, ok := weekdayCodes[code]
	if !ok {
		return weekdayNum{}, false
	}

	out := weekdayNum{day: day}
	if prefix := s[:len(s)-2]; prefix != "" {
		n, err := strconv.Atoi(prefix)
		if err != nil {
			return weekdayNum{}, false
		}
		out.ord = n
	}
	return out, true
}
